### ISSUE TITLE
Specify app versions

### ISSUE THREAD

**Issue by belal-i** [belal-i/docksible#35]
Currently, for whatever app Docksible is installing, the latest image will be pulled.

Example: Redmine
```yaml
  docksible_redmine:
    image: redmine
...
```

Example: WordPress
```yaml
  docksible_wordpress:
    depends_on:
      - docksible_db
    container_name: docksible_wordpress
    image: wordpress:latest
    restart: unless-stopped
...
```

It would be good to have some CLI flag like `--app-version`, to specify the version of whatever image will be pulled.

It should default to `latest`, and we should have some validation in place to make sure the user doesn't try to pull an image that doesn't exist.

I will try to update this with more exact requirements soon.
